name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: login
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Build the Docker image
      run: docker build . --file ./Dockerfile --tag ghcr.io/$GITHUB_ACTOR/data-science-py:latest
    
    - name: Push Docker Image
      run: |
        docker push ghcr.io/$GITHUB_ACTOR/data-science-py:latest